### PR TITLE
Add configs

### PR DESCRIPTION
**Pull request by ybiquitous**
Based on <https://www.npmjs.com/search?q=keywords%3Astylelint-config&ranking=popularity>

### CODE REVIEW

**Comment by Mouvedia** [comment]
Some of the tests show up as passed but have failed.
It's probably not related to Stylelint though.
e.g. https://github.com/ybiquitous/stylelint-ecosystem-tester/actions/runs/9903277646/job/27358541572 is probably missing `--experimental-vm-modules`

**Comment by ybiquitous** [comment]
Right. I believe most errors are unrelated to Stylelint: failed repositories' problems.

We can suggest a fix in such repositories or just remove them from this test suite. In my personal opinion, the former is preferred, though.

**Comment by Mouvedia** [comment]
> I believe most errors are unrelated to Stylelint: failed repositories' problems.

👍 

Some are even failing at the `install` step though.
e.g. https://github.com/ybiquitous/stylelint-ecosystem-tester/actions/runs/9903277646/job/27358550823
Anyhow, this list of packages is a good starting point but we need to be careful about the passing state, it's not reliable.

**Comment by ybiquitous** [comment]
We can see all errors and warnings in the annotation list in one page.
E.g. https://github.com/ybiquitous/stylelint-ecosystem-tester/actions/runs/9903754245

image

**Pull request merged**
